In [26]:
import torch

In [27]:
x = torch.rand((2,3),dtype=torch.float64)

In [28]:
print(x.size(0))
print(x.type())
print(x.shape)

2
torch.DoubleTensor
torch.Size([2, 3])


In [29]:
X = x.numpy()
print(X)

[[0.06279363 0.17760308 0.67674725]
 [0.90175786 0.15314153 0.51152676]]


In [30]:
y = torch.from_numpy(X)
print(y)

tensor([[0.0628, 0.1776, 0.6767],
        [0.9018, 0.1531, 0.5115]], dtype=torch.float64)


In [34]:
x+x
x.add(x)

tensor([[0.5023, 1.4208, 5.4140],
        [7.2141, 1.2251, 4.0922]], dtype=torch.float64)

In [35]:
x.add_(x)

tensor([[0.5023, 1.4208, 5.4140],
        [7.2141, 1.2251, 4.0922]], dtype=torch.float64)

In [37]:
print(x.view(3,2))
print(x.view(-1,1))

tensor([[0.5023, 1.4208],
        [5.4140, 7.2141],
        [1.2251, 4.0922]], dtype=torch.float64)
tensor([[0.5023],
        [1.4208],
        [5.4140],
        [7.2141],
        [1.2251],
        [4.0922]], dtype=torch.float64)


In [49]:
print(x.mean())
y = x.mean()
print(torch.tensor([1]))
print(y.item())
print(torch.tensor([1]).item())
#两者有什么区别

tensor(3.3114, dtype=torch.float64)
tensor([1])
3.3114268151557895
1
